version: "3"
services:
  frontend:
    image: node:18-alpine
    container_name: vite-react-app
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host"
    restart: always
    environment:
      - CHOKIDAR_USEPOLLING=true

  api:
    image: node:18-alpine
    container_name: node-api
    working_dir: /app
    volumes:
      - ./server:/app
    ports:
      - "3000:3000"
    command: npm start
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://mongo:27017/flightapp"
      JWT_SECRET: "Wv+AopoPW8nO3amsja11PK5szgSnpboWfsbE1nzcyYo="
    restart: always

  mongo:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
    restart: always
